---
title: "TidyTuesday 2021/08: Du Bois Challenge"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, comment = "#>",
                      fig.path = "figs/", dpi = 300, dev = "ragg_png",
                      dev.args = list(bg = "transparent"))
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
```

```{r load, message=FALSE}
library(tidyverse)
library(magick)
```

```{r data}
orig <- "https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/challenge/challenge06/original-plate-11.jpg" %>% 
  image_read()

bg_img <- "https://upload.wikimedia.org/wikipedia/commons/8/86/Tattered_Edges.png" %>% 
  # Originally posted to Flickr by Playingwithbrushes at
  # https://flickr.com/photos/82518118@N00/2926159152
  image_read() %>% 
  image_fill(color = "transparent", refcolor = "white", fuzz = 4) %>% 
  image_modulate(brightness = 150) %>% 
  image_flip() %>% 
  image_raster(tidy = FALSE)

city_rural <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-16/city_rural.csv" %>% 
  readr::read_csv()

pop_lineend <- 9e4

lines_data <- city_rural %>% 
  mutate(Population = if_else(Category == last(Category), pop_lineend, Population),
         colour = c("#406C5C", "#5472A8", "#F2B100", "#D4273F"),
         angle = c(0, 135, 45, 135)) %>% 
  `[<-`(c("x", "xend", "y", "yend"), value = NA_real_)

# This is clunky
for (i in seq_len(nrow(lines_data))) {
  lines_data <- lines_data %>% 
    mutate(x = if_else(row_number() == i, lag(xend, default = 0), x),
           xend = if_else(row_number() == i,
                          x + Population * cos(2 * pi * angle / 360),
                          xend),
           y = if_else(row_number() == i, lag(yend, default = 0), y),
           yend = if_else(row_number() == i,
                          y + Population * sin(2 * pi * angle / 360),
                          yend))
}

spiral_data <- tibble(a = 1e4,
                      b = 857.26, # Trial and error - to get correct spiral length
                      theta = seq(0, 9 * pi, length = 1e4) -
                        2 * pi * -45 / 360, # Rotate 45° CCW
                      r = a + b * theta,
                      x = r * cos(theta),
                      y = r * sin(theta)) %>%
  # Spiral starts at end of last line:
  mutate(x = x + last(lines_data$xend) - last(x),
         y = y + last(lines_data$yend) - last(y))

# Check spiral length:
# last(city_rural$Population) - pop_lineend
# spiral_data %>% 
#   mutate(dist = sqrt((x - lag(x))^2 + (y - lag(y))^2)) %>%
#   summarise(sum(dist, na.rm = TRUE)) # Close enough
```

```{r plot, fig.width=8, fig.height=10, optipng=''}
lines_data %>% 
  ggplot(aes(x, y)) +
  annotation_raster(bg_img, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  geom_segment(aes(xend = xend, yend = yend),
               lineend = "round", size = 2.1, show.legend = FALSE) +
  geom_path(data = spiral_data,
            size = 2.1, lineend = "round") +
  geom_segment(aes(xend = xend, yend = yend, colour = colour),
               lineend = "round", size = 2, show.legend = FALSE) +
  geom_path(data = spiral_data,
            colour = last(lines_data$colour), size = 2, lineend = "round") +
  scale_x_continuous(limits = c(-5e4, 17e4)) +
  scale_y_reverse(limits = c(23e4, -6e4)) +
  scale_colour_identity() +
  coord_equal() +
  annotate("text", x = mean(c(-5e4, 17e4)), y = -5e4,
           label = "CITY AND RURAL POPULATION.\n1890.",
           family = "Airborne II Pilot", size = 6) +
  annotate("text", x = 22e3, y = 4e3,
           label = paste(format(city_rural$Population[1], big.mark = ","),
                         "NEGROES IN CITIES\nOF OVER 10,000 INHABITANTS"),
           family = "Airborne II Pilot", size = 2.5, lineheight = .75,
           colour = "grey20") +
  annotate("text", x = lines_data$x[2], y = 4e3,
           label = paste(format(city_rural$Population[2], big.mark = ","),
                         "NEGROES IN CITIES\n FROM 5,000 TO 10,000"),
           family = "Airborne II Pilot", size = 2.5, lineheight = .75,
           hjust = "left", colour = "grey20") +
  annotate("text", x = lines_data$x[3], y = mean(lines_data$y[3:4]),
           label = paste(format(city_rural$Population[3], big.mark = ","),
                         "\nNEGROES\nIN CITIES\n FROM\n2,500 TO 5,000"),
           family = "Airborne II Pilot", size = 2.5, lineheight = .75,
           colour = "grey20") +
  annotate("text", x = spiral_data$x[1] - 7e3, y = spiral_data$y[1] - 8e3,
           label = format(city_rural$Population[4], big.mark = ","),
           family = "Airborne II Pilot", size = 2.5, colour = "grey20") +
  annotate("text", x = mean(c(-5e4, 17e4)), y = max(spiral_data$y) + 4e3,
           label = toupper(paste("negroes living in the", city_rural$Category[4])),
           family = "Airborne II Pilot", size = 2.5, colour = "grey20") +
  annotate("text", x = mean(c(-5e4, 17e4)), y = 23e4,
           label = "Long Nguyen (@long39ng) · #DuboisChallenge",
           family = "Courier", fontface = "bold", size = 2.5) +
  theme_void()
```

<details><summary>Session information</summary>
```{r sesh}
sessionInfo()
```
</details>
