---
title: "TidyTuesday 2021/11: Bechdel Test"
output: github_document
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, collapse = TRUE, comment = "#>",
  fig.path = "figs/", dpi = 300,
  dev = "ragg_png", dev.args = list(bg = "black")
)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)

library(tidyverse)
library(scales)
```

```{r prep, eval=FALSE}
library(furrr)
library(omdbapi)

raw_bechdel <- read_csv("https://github.com/rfordatascience/tidytuesday/raw/master/data/2021/2021-03-09/raw_bechdel.csv",
  col_types = "iicci"
) %>%
  mutate(imdb_id = paste0("tt", imdb_id))

omdb_api_keys <- vector("character", length = 9L) # Redacted

plan(multisession)

bechdel <- raw_bechdel %>%
  mutate(group = sort(rep(1:9, 1000))[1:nrow(bechdel)]) %>%
  group_split(group) %>%
  future_map2_dfr(.y = omdb_api_keys, ~ mutate(.x, genre = map(
    imdb_id,
    possibly(function(id) {
      get_genres(find_by_id(id, api_key = .y))
    }, otherwise = NULL)
  ))) %>%
  select(-group)

saveRDS(bechdel, here::here("2021_11_bechdel_test/bechdel.RDS"))
```

```{r palette}
# Source: https://twitter.com/maxnoethe/status/1176398931208671232
stripes_pal <- c(
  brewer_pal(palette = "Reds", direction = -1)(9)[2:8],
  brewer_pal(palette = "Blues")(9)[2:8]
)
```

```{r data}
bechdel <- readRDS(here::here("2021_11_bechdel_test/bechdel.RDS"))

# Take care of duplicates
bechdel %>%
  add_count(year, title) %>%
  filter(n > 1)
# There were actually two different Dracula (Drácula) movies in 1931 :D
# What's up with Terms of Endearment tho?

bechdel_long <- bechdel %>%
  mutate(n_genres = map_int(genre, length)) %>%
  filter(n_genres > 0) %>%
  distinct(year, title, rating, .keep_all = TRUE) %>%
  select(-n_genres) %>%
  unnest(genre)

bechdel_long %>%
  count(genre) %>%
  arrange(n)
```

```{r strips, message=FALSE, fig.width=11, fig.height=7, optipng=''}
theme_set(
  theme_void(base_size = 13, base_family = "Inter Medium") +
    theme(
      text = element_text(colour = "white"),
      legend.position = "top",
      strip.text = element_text(
        family = "Inter Semi Bold",
        size = rel(1),
        margin = margin(b = 1)
      ),
      plot.title = element_text(
        family = "Metropolis Extra Bold",
        size = rel(2)
      ),
      plot.subtitle = ggtext::element_textbox_simple(
        size = rel(1.4),
        margin = margin(t = 10, b = 15)
      ),
      plot.caption = element_text(
        margin = margin(t = 20)
      ),
      plot.background = element_rect(fill = "black"),
      plot.margin = margin(15, 20, 15, 20)
    )
)

stripes <- bechdel_long %>%
  add_count(genre) %>%
  filter(n > 10) %>%
  mutate(pass = if_else(rating == 3, 1L, 0L)) %>%
  slice(sort(rep(seq_len(nrow(bechdel_long)), 2))) %>%
  mutate(genre = if_else(row_number() %% 2 == 0, "OVERALL", genre)) %>%
  group_by(genre, year) %>%
  summarise(prop_pass = mean(pass)) %>%
  ungroup() %>%
  ggplot(aes(year, 1, fill = prop_pass)) +
  geom_tile() +
  scale_fill_gradientn(
    colours = stripes_pal,
    breaks = c(0, 1),
    labels = label_percent(),
    guide = guide_colourbar(
      title = NULL,
      label.hjust = c(1.5, -.3),
      label.vjust = 6.5,
      barwidth = 7,
      barheight = .3,
      ticks = FALSE
    )
  ) +
  facet_wrap(~ fct_reorder(genre, prop_pass, mean) %>%
    fct_relevel("OVERALL", after = Inf),
  ncol = 6
  ) +
  labs(
    title = "Cooling Stripes?",
    subtitle = glue::glue("Percentage of movies having at least two women who talk to each other about something other than a man, {min(bechdel$year)}–{max(bechdel$year)}"),
    caption = "Data: IMDb/OMDb & BechdelTest.com — Graphic: Long Nguyen (@long39ng) — #TidyTuesday"
  )

stripes
```

<details><summary>Session information</summary>
```{r sesh}
sessionInfo()
```
</details>
